name: Basic-Schulung
on:
  workflow_dispatch:

jobs:
 build:
  name: My first Action
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - uses: ./action-a
      with:
        MY_NAME: ${{ secrets.SECRET_NAME }}    
